/* tslint:disable */
/* eslint-disable */
/**
 * Dji.Server
 * 让大疆上云 开发更简单、更通用、更流行。前后端分离架构(.NET8/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://github.com/guipie/dji_server/'>https://github.com/guipie/dji_server</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 15100305@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 增加订阅消息模板
 * @export
 * @interface AddSubscribeMessageTemplateInput
 */
export interface AddSubscribeMessageTemplateInput {
	/**
	 * 模板标题Id
	 * @type {string}
	 * @memberof AddSubscribeMessageTemplateInput
	 */
	templateTitleId: string;
	/**
	 * 模板关键词列表,例如 [3,5,4]
	 * @type {Array<number>}
	 * @memberof AddSubscribeMessageTemplateInput
	 */
	keyworkIdList: Array<number>;
	/**
	 * 服务场景描述，15个字以内
	 * @type {string}
	 * @memberof AddSubscribeMessageTemplateInput
	 */
	sceneDescription: string;
}
