/* tslint:disable */
/* eslint-disable */
/**
 * Dji.Server
 * 让大疆上云 开发更简单、更通用、更流行。前后端分离架构(.NET8/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://github.com/guipie/dji_server/'>https://github.com/guipie/dji_server</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 15100305@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ConstOutput
 */
export interface ConstOutput {
	/**
	 * 名称
	 * @type {string}
	 * @memberof ConstOutput
	 */
	name?: string | null;
	/**
	 * 编码
	 * @type {any}
	 * @memberof ConstOutput
	 */
	code?: any | null;
	/**
	 * 扩展字段
	 * @type {any}
	 * @memberof ConstOutput
	 */
	data?: any | null;
}
