/* tslint:disable */
/* eslint-disable */
/**
 * Dji.Server
 * 让大疆上云 开发更简单、更通用、更流行。前后端分离架构(.NET8/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://github.com/guipie/dji_server/'>https://github.com/guipie/dji_server</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 15100305@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CreateEntityInput
 */
export interface CreateEntityInput {
	/**
	 * 表名
	 * @type {string}
	 * @memberof CreateEntityInput
	 */
	tableName?: string | null;
	/**
	 * 实体名
	 * @type {string}
	 * @memberof CreateEntityInput
	 */
	entityName?: string | null;
	/**
	 * 基类名
	 * @type {string}
	 * @memberof CreateEntityInput
	 */
	baseClassName?: string | null;
	/**
	 * 导出位置
	 * @type {string}
	 * @memberof CreateEntityInput
	 */
	position?: string | null;
	/**
	 * 库标识
	 * @type {string}
	 * @memberof CreateEntityInput
	 */
	configId?: string | null;
}
