/* tslint:disable */
/* eslint-disable */
/**
 * Dji.Server
 * 让大疆上云 开发更简单、更通用、更流行。前后端分离架构(.NET8/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://github.com/guipie/dji_server/'>https://github.com/guipie/dji_server</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 15100305@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 枚举类型输出参数
 * @export
 * @interface EnumTypeOutput
 */
export interface EnumTypeOutput {
	/**
	 * 枚举类型描述
	 * @type {string}
	 * @memberof EnumTypeOutput
	 */
	typeDescribe?: string | null;
	/**
	 * 枚举类型名称
	 * @type {string}
	 * @memberof EnumTypeOutput
	 */
	typeName?: string | null;
	/**
	 * 枚举类型备注
	 * @type {string}
	 * @memberof EnumTypeOutput
	 */
	typeRemark?: string | null;
}
