/* tslint:disable */
/* eslint-disable */
/**
 * Dji.Server
 * 让大疆上云 开发更简单、更通用、更流行。前后端分离架构(.NET8/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://github.com/guipie/dji_server/'>https://github.com/guipie/dji_server</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 15100305@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 获取消息模板列表
 * @export
 * @interface MessageTemplateSendInput
 */
export interface MessageTemplateSendInput {
	/**
	 * 订阅模板Id
	 * @type {string}
	 * @memberof MessageTemplateSendInput
	 */
	templateId: string;
	/**
	 * 接收者的OpenId
	 * @type {string}
	 * @memberof MessageTemplateSendInput
	 */
	toUserOpenId: string;
	/**
	 * 模板跳转链接
	 * @type {string}
	 * @memberof MessageTemplateSendInput
	 */
	url?: string | null;
	/**
	 * 所需跳转到小程序的具体页面路径，支持带参数,（示例index?foo=bar）
	 * @type {string}
	 * @memberof MessageTemplateSendInput
	 */
	miniProgramPagePath?: string | null;
}
