/* tslint:disable */
/* eslint-disable */
/**
 * Dji.Server
 * 让大疆上云 开发更简单、更通用、更流行。前后端分离架构(.NET8/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://github.com/guipie/dji_server/'>https://github.com/guipie/dji_server</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 15100305@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TenantOutput } from './tenant-output';
/**
 * 分页泛型集合
 * @export
 * @interface SqlSugarPagedListTenantOutput
 */
export interface SqlSugarPagedListTenantOutput {
	/**
	 * 页码
	 * @type {number}
	 * @memberof SqlSugarPagedListTenantOutput
	 */
	page?: number;
	/**
	 * 页容量
	 * @type {number}
	 * @memberof SqlSugarPagedListTenantOutput
	 */
	pageSize?: number;
	/**
	 * 总条数
	 * @type {number}
	 * @memberof SqlSugarPagedListTenantOutput
	 */
	total?: number;
	/**
	 * 总页数
	 * @type {number}
	 * @memberof SqlSugarPagedListTenantOutput
	 */
	totalPages?: number;
	/**
	 * 当前页集合
	 * @type {Array<TenantOutput>}
	 * @memberof SqlSugarPagedListTenantOutput
	 */
	items?: Array<TenantOutput> | null;
	/**
	 * 是否有上一页
	 * @type {boolean}
	 * @memberof SqlSugarPagedListTenantOutput
	 */
	hasPrevPage?: boolean;
	/**
	 * 是否有下一页
	 * @type {boolean}
	 * @memberof SqlSugarPagedListTenantOutput
	 */
	hasNextPage?: boolean;
}
