/* tslint:disable */
/* eslint-disable */
/**
 * Dji.Server
 * 让大疆上云 开发更简单、更通用、更流行。前后端分离架构(.NET8/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://github.com/guipie/dji_server/'>https://github.com/guipie/dji_server</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 15100305@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NoticeUserStatusEnum } from './notice-user-status-enum';
import { SysNotice } from './sys-notice';
/**
 * 系统通知公告用户表
 * @export
 * @interface SysNoticeUser
 */
export interface SysNoticeUser {
	/**
	 * 通知公告Id
	 * @type {number}
	 * @memberof SysNoticeUser
	 */
	noticeId?: number;
	/**
	 *
	 * @type {SysNotice}
	 * @memberof SysNoticeUser
	 */
	sysNotice?: SysNotice;
	/**
	 * 用户Id
	 * @type {number}
	 * @memberof SysNoticeUser
	 */
	userId?: number;
	/**
	 * 阅读时间
	 * @type {Date}
	 * @memberof SysNoticeUser
	 */
	readTime?: Date | null;
	/**
	 *
	 * @type {NoticeUserStatusEnum}
	 * @memberof SysNoticeUser
	 */
	readStatus?: NoticeUserStatusEnum;
}
