/* tslint:disable */
/* eslint-disable */
/**
 * Dji.Server
 * 让大疆上云 开发更简单、更通用、更流行。前后端分离架构(.NET8/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://github.com/guipie/dji_server/'>https://github.com/guipie/dji_server</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 15100305@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StatusEnum } from './status-enum';
/**
 *
 * @export
 * @interface UpdatePluginInput
 */
export interface UpdatePluginInput {
	/**
	 * 雪花Id
	 * @type {number}
	 * @memberof UpdatePluginInput
	 */
	id?: number;
	/**
	 * 创建时间
	 * @type {Date}
	 * @memberof UpdatePluginInput
	 */
	createTime?: Date | null;
	/**
	 * 更新时间
	 * @type {Date}
	 * @memberof UpdatePluginInput
	 */
	updateTime?: Date | null;
	/**
	 * 创建者Id
	 * @type {number}
	 * @memberof UpdatePluginInput
	 */
	createUserId?: number | null;
	/**
	 * 修改者Id
	 * @type {number}
	 * @memberof UpdatePluginInput
	 */
	updateUserId?: number | null;
	/**
	 * 软删除
	 * @type {boolean}
	 * @memberof UpdatePluginInput
	 */
	isDelete?: boolean;
	/**
	 * 租户Id
	 * @type {number}
	 * @memberof UpdatePluginInput
	 */
	tenantId?: number | null;
	/**
	 * C#代码
	 * @type {string}
	 * @memberof UpdatePluginInput
	 */
	csharpCode: string;
	/**
	 * 程序集名称
	 * @type {string}
	 * @memberof UpdatePluginInput
	 */
	assemblyName?: string | null;
	/**
	 * 排序
	 * @type {number}
	 * @memberof UpdatePluginInput
	 */
	orderNo?: number;
	/**
	 *
	 * @type {StatusEnum}
	 * @memberof UpdatePluginInput
	 */
	status?: StatusEnum;
	/**
	 * 备注
	 * @type {string}
	 * @memberof UpdatePluginInput
	 */
	remark?: string | null;
	/**
	 * 名称
	 * @type {string}
	 * @memberof UpdatePluginInput
	 */
	name: string;
}
